name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}

          script: |
            set -e

            echo "📂 Enter project"
            cd /var/www/jvalleyverse-go

            echo "⬇️ Pull latest code"
            git fetch origin
            git reset --hard origin/main

            echo "📦 Download dependencies"
            go mod download

            echo "🔨 Build binary"
            go build -o service ./cmd/api

            echo "🔄 Restart service"
            sudo systemctl restart jvalleyverse-go

            echo "✅ Check service"
            sudo systemctl is-active jvalleyverse-go
